language: node_js
node_js:
  - "stable"
case:
  directories:
  - node_modules
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local_dir: build
  on:
    branch: master